// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Amazon;
using Amazon.Lambda.Core;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using System.Threading.Tasks;

[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]
namespace MultiResidence
{
	public class Function
	{
		// Cache the model store for use by subsequent
		// executions of this lambda.
		private IModelStore<MultiResidenceInputs> store;

		public async Task<MultiResidenceOutputs> Handler(MultiResidenceInputs args, ILambdaContext context)
		{
			if(this.store == null)
			{
				this.store = new S3ModelStore<MultiResidenceInputs>(RegionEndpoint.USWest1);
			}
			
			var l = new InvocationWrapper<MultiResidenceInputs,MultiResidenceOutputs>(store, MultiResidence.Execute);
			var output = await l.InvokeAsync(args);
			return output;
		}
  	}
}