// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace MultiResidence
{
	public class MultiResidenceOutputs: ResultsBase
	{
		/// <summary>
		/// Quantity of Residences.
		/// </summary>
		[JsonProperty("Residence Quantity")]
		public double ResidenceQuantity {get;}

		/// <summary>
		/// Aggregate area of all residences.
		/// </summary>
		[JsonProperty("Total Area")]
		public double TotalArea {get;}

		/// <summary>
		/// Site coverage ratio.
		/// </summary>
		[JsonProperty("Site Coverage")]
		public double SiteCoverage {get;}

		/// <summary>
		/// Height of building.
		/// </summary>
		[JsonProperty("Building Height")]
		public double BuildingHeight {get;}


		
		/// <summary>
		/// Construct a MultiResidenceOutputs with default inputs.
		/// This should be used only for testing.
		/// </summary>
		public MultiResidenceOutputs() : base()
		{

		}
		
		/// <summary>
		/// Construct a MultiResidenceOutputs specifying all inputs.
		/// </summary>
		/// <returns></returns>
		[JsonConstructor]
		public MultiResidenceOutputs(double residencequantity, double totalarea, double sitecoverage, double buildingheight): base()
		{
			this.ResidenceQuantity = residencequantity;
			this.TotalArea = totalarea;
			this.SiteCoverage = sitecoverage;
			this.BuildingHeight = buildingheight;

		}
	}
}